use_frameworks!

platform :ios, '11.0'

target 'MinipaySDK_Example' do
#  pod 'MinipaySDK', '~> 1.0.2'
  pod 'MinipaySDK', :path => '../'
  pod 'SnapKit', '~> 5.0.0'

  target 'MinipaySDK_Tests' do
    inherit! :search_paths

  end
end
